#include <atomic>
#include <chrono>
#include <filesystem>
#include <fstream>

#include <windows.h>
#include <ShlObj.h>

#include <initguid.h>
#include <Dbt.h>

#include <spdlog/sinks/basic_file_sink.h>

#include <imgui.h>
#include <imgui_freetype.h>
#include <ImGuizmo.h>
#include <imnodes.h>
#include "re2-imgui/imgui_impl_dx11.h"
#include "re2-imgui/imgui_impl_dx12.h"
#include "re2-imgui/imgui_impl_win32.h"

#include "utility/Module.hpp"
#include "utility/Patch.hpp"
#include "utility/Scan.hpp"
#include "utility/Thread.hpp"

#include "Mods.hpp"
#include "mods/FaultyFileDetector.hpp"
#include "mods/LooseFileLoader.hpp"
#include "mods/PluginLoader.hpp"
#include "sdk/REGlobals.hpp"
#include "sdk/Application.hpp"
#include "sdk/SDK.hpp"

#include "ExceptionHandler.hpp"
#include "mods/REFrameworkConfig.hpp"
#include "mods/IntegrityCheckBypass.hpp"
#include "CommitHash.autogenerated"
#include "REFramework.hpp"

#include "core/StartupPipeline.hpp"
#include "core/D3DHookMonitor.hpp"
#include "input/InputManager.hpp"
#include "render/FrameRenderer.hpp"

namespace fs = std::filesystem;
using namespace std::literals;

// ---------------------------------------------------------------------------
// Named timeouts / limits — replace magic numbers scattered through the file.
// ---------------------------------------------------------------------------
static constexpr auto PRESENT_TIMEOUT     = std::chrono::seconds{5};
static constexpr auto CHANCE_TIMEOUT      = std::chrono::seconds{1};
static constexpr auto MESSAGE_TIMEOUT     = std::chrono::seconds{5};
static constexpr auto SENDMESSAGE_TIMEOUT = std::chrono::seconds{1};
static constexpr auto INIT_FRAME_DELAY    = 60;
static constexpr auto MAX_SCAN_RETRIES    = 10;
static constexpr auto VM_INIT_TIMEOUT     = std::chrono::seconds{30};
static constexpr auto NUM_COMMAND_CONTEXTS = 3;

extern IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandler(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam);
DEFINE_GUID(GUID_DEVINTERFACE_HID, 0x4D1E55B2L, 0xF16F, 0x11CF, 0x88, 0xCB, 0x00, 0x11, 0x11, 0x00, 0x00, 0x30);
DEFINE_GUID(XUSB_INTERFACE_CLASS_GUID, 0xEC87F1E3, 0xC13B, 0x4100, 0xB5, 0xF7, 0x8B, 0x84, 0xD5, 0x42, 0x60, 0xCB);

std::unique_ptr<REFramework> g_framework{};

// ---------------------------------------------------------------------------
// LDR notification types & callback
// ---------------------------------------------------------------------------
typedef struct _LDR_DLL_UNLOADED_NOTIFICATION_DATA {
    ULONG Flags;
    PCUNICODE_STRING FullDllName;
    PCUNICODE_STRING BaseDllName;
    PVOID DllBase;
    ULONG SizeOfImage;
} LDR_DLL_UNLOADED_NOTIFICATION_DATA, *PLDR_DLL_UNLOADED_NOTIFICATION_DATA;

typedef struct _LDR_DLL_LOADED_NOTIFICATION_DATA {
    ULONG Flags;
    PCUNICODE_STRING FullDllName;
    PCUNICODE_STRING BaseDllName;
    PVOID DllBase;
    ULONG SizeOfImage;
} LDR_DLL_LOADED_NOTIFICATION_DATA, *PLDR_DLL_LOADED_NOTIFICATION_DATA;

typedef union _LDR_DLL_NOTIFICATION_DATA {
    LDR_DLL_LOADED_NOTIFICATION_DATA Loaded;
    LDR_DLL_UNLOADED_NOTIFICATION_DATA Unloaded;
} LDR_DLL_NOTIFICATION_DATA, *PLDR_DLL_NOTIFICATION_DATA;

using PLDR_DLL_NOTIFICATION_FUNCTION = void (*)(
  ULONG                       NotificationReason,
  PLDR_DLL_NOTIFICATION_DATA NotificationData,
  PVOID                       Context
);

using LdrRegisterDllNotification_t = NTSTATUS (*) (
    ULONG                          Flags,
    PLDR_DLL_NOTIFICATION_FUNCTION NotificationFunction,
    PVOID                          Context,
    PVOID                          *Cookie
);

#define LDR_DLL_NOTIFICATION_REASON_LOADED 1
#define LDR_DLL_NOTIFICATION_REASON_UNLOADED 2

std::optional<std::filesystem::path> g_current_game_path{};
bool g_success_made_ldr_notification{false};

void CALLBACK ldr_notification_callback(
    ULONG                       NotificationReason,
    PLDR_DLL_NOTIFICATION_DATA NotificationData,
    PVOID                       Context
) 
try {
    if (NotificationReason == LDR_DLL_NOTIFICATION_REASON_LOADED) {
        if (NotificationData->Loaded.BaseDllName != nullptr && NotificationData->Loaded.BaseDllName->Buffer != nullptr) {
            std::wstring base_dll_name = NotificationData->Loaded.BaseDllName->Buffer;
            std::wstring lower_base_dll_name = base_dll_name;
            std::transform(lower_base_dll_name.begin(), lower_base_dll_name.end(), lower_base_dll_name.begin(), ::towlower);
            spdlog::info("LdrRegisterDllNotification: Loaded: {}", utility::narrow(base_dll_name));

            if (lower_base_dll_name.find(L"sl.dlss_g.dll") != std::wstring::npos) {
                spdlog::info("LdrRegisterDllNotification: Detected DLSS DLL loaded");
                D3D12Hook::hook_streamline((HMODULE)NotificationData->Loaded.DllBase);
            }
        }

        if (g_current_game_path && NotificationData->Loaded.FullDllName != nullptr && NotificationData->Loaded.FullDllName->Buffer != nullptr) {
            std::wstring full_dll_name = NotificationData->Loaded.FullDllName->Buffer;
            std::filesystem::path full_dll_path = full_dll_name;

            if (full_dll_path.parent_path() == *g_current_game_path) {
                spdlog::info("LdrRegisterDllNotification: DLL loaded from game directory: {}", utility::narrow(full_dll_name));

#if defined(DD2) || defined(MHRISE) || TDB_VER >= 74
                utility::spoof_module_paths_in_exe_dir();
#endif
            }
        } else {
            spdlog::info("LdrRegisterDllNotification: DLL loaded from unknown location");
        }
    }
} catch (const std::exception& e) {
    spdlog::error("ldr_notification_callback: Exception occurred: {}", e.what());
} catch(...) {
    spdlog::error("ldr_notification_callback: Unknown exception occurred");
}

// ---------------------------------------------------------------------------
// Construction
// ---------------------------------------------------------------------------
REFramework::REFramework(HMODULE reframework_module)
    : m_game_module{GetModuleHandle(0)}
    , m_logger{spdlog::basic_logger_mt("REFramework", (get_persistent_dir("reframework_log.txt")).string(), true)}
    , m_hook_monitor{std::make_unique<D3DHookMonitor>(*this)}
    , m_input_manager{std::make_unique<InputManager>(*this)}
{
    s_reframework_module = reframework_module;
    std::scoped_lock __{m_startup_mutex};

    spdlog::set_default_logger(m_logger);
    spdlog::flush_on(spdlog::level::info);

    StartupPipeline()
        .add("logging", [](REFramework& fw) { fw.setup_logging(); return true; })
        .add("game_path", [](REFramework& fw) { fw.detect_game_path(); return true; })
        .add("hook_buffer", [](REFramework& fw) { fw.preallocate_hook_buffer(); return true; })
        .add("os_version", [](REFramework& fw) { fw.detect_os_version(); return true; })
        .add("storage_files", [](REFramework& fw) { fw.copy_storage_files(); return true; })
        .add("ldr_notification", [](REFramework& fw) { fw.register_ldr_notification(); return true; })
        .add("wait_d3d", [](REFramework& fw) { fw.wait_for_d3d_if_packed(); return true; })
        .add("vr_dlls", [](REFramework& fw) { fw.load_vr_dlls(); return true; })
        .add("re8_crash_fix", [](REFramework& fw) { fw.setup_re8_crash_fix(); return true; })
        .add("mhwilds_early_init", [](REFramework& fw) { fw.setup_mhwilds_early_init(); return true; })
        .add("integrity_bypass", [](REFramework& fw) { fw.setup_integrity_bypass(); return true; })
        .add("plugin_early_init", [](REFramework& fw) { fw.plugin_early_init(); return true; })
        .add("vm_renderer", [](REFramework& fw) { fw.wait_for_vm_and_renderer(); return true; })
        .add("monitor_thread", [](REFramework& fw) { fw.start_monitor_thread(); return true; })
        .run(*this);
}

// ---------------------------------------------------------------------------
// Private construction helpers
// ---------------------------------------------------------------------------

void REFramework::setup_logging() {
    if (s_fallback_appdata) {
        spdlog::warn("Failed to write to current directory, falling back to appdata folder");
    }

    spdlog::info("REFramework entry");
    spdlog::info("Commit hash: {}", REF_COMMIT_HASH);
    spdlog::info("Tag: {}", REF_TAG);
    spdlog::info("Commits past tag: {}", REF_COMMITS_PAST_TAG);
    spdlog::info("Branch: {}", REF_BRANCH);
    spdlog::info("Total commits: {}", REF_TOTAL_COMMITS);
    spdlog::info("Build date: {}", REF_BUILD_DATE);
    spdlog::info("Build time: {}", REF_BUILD_TIME);
    spdlog::info("Game name: {}", REFramework::get_game_name());

    IMGUI_CHECKVERSION();
    ImGui::CreateContext();

#ifdef DEBUG
    spdlog::set_level(spdlog::level::debug);
#else
    spdlog::set_level(spdlog::level::warn);
#endif
}

void REFramework::detect_game_path() {
    const auto module_size = *utility::get_module_size(m_game_module);

    spdlog::info("Game Module Addr: {:x}", (uintptr_t)m_game_module);
    spdlog::info("Game Module Size: {:x}", module_size);

    if (auto current_game_path = utility::get_module_pathw(m_game_module); current_game_path.has_value()) {
        g_current_game_path = *current_game_path;
        g_current_game_path = g_current_game_path->parent_path();
        spdlog::info("Current game path: {}", utility::narrow(g_current_game_path->c_str()));
    }
}

void REFramework::preallocate_hook_buffer() {
    const auto halfway_module = (uintptr_t)m_game_module + (*utility::get_module_size(m_game_module) / 2);

    static auto sh_allocator = safetyhook::Allocator::global();
    intptr_t requested_size = 1 * 1024 * 1024;
    while (requested_size > 0 && !sh_allocator->allocate_near({(uint8_t*)halfway_module}, requested_size)) {
        requested_size -= 0x1000;
    }

    spdlog::info("Preallocated buffer near {:x}", halfway_module);

    IntegrityCheckBypass::fix_virtual_protect();
}

void REFramework::detect_os_version() {
    typedef LONG (*RtlGetVersionFunc)(PRTL_OSVERSIONINFOW);

    const auto ntdll = GetModuleHandle("ntdll.dll");
    if (ntdll == nullptr) {
        spdlog::info("ntdll.dll not found");
        return;
    }

    auto rtl_get_version = (RtlGetVersionFunc)GetProcAddress(ntdll, "RtlGetVersion");
    if (rtl_get_version == nullptr) {
        spdlog::info("RtlGetVersion() not found");
        return;
    }

    spdlog::info("Getting OS version information...");

    OSVERSIONINFOW os_version_info{};
    ZeroMemory(&os_version_info, sizeof(OSVERSIONINFOW));
    os_version_info.dwOSVersionInfoSize = sizeof(OSVERSIONINFOW);

    if (rtl_get_version(&os_version_info) != 0) {
        spdlog::info("RtlGetVersion() failed");
    } else {
        spdlog::info("OS Version Information");
        spdlog::info("\tMajor Version: {}", os_version_info.dwMajorVersion);
        spdlog::info("\tMinor Version: {}", os_version_info.dwMinorVersion);
        spdlog::info("\tBuild Number: {}", os_version_info.dwBuildNumber);
        spdlog::info("\tPlatform Id: {}", os_version_info.dwPlatformId);

        spdlog::info("Disclaimer: REFramework does not send this information to the developers or any other third party.");
        spdlog::info("This information is only used to help with the development of REFramework.");
    }
}

void REFramework::copy_storage_files() {
#if defined(DD2) || defined(MHRISE) || TDB_VER >= 74
    if (!g_current_game_path.has_value()) return;

    const auto dest_path = *g_current_game_path / "_storage_";
    fs::create_directories(dest_path);

    if (!std::filesystem::exists(dest_path)) {
        spdlog::error("Failed to create storage directory");
        return;
    }

    auto copy_file_safe = [](const fs::path& src, const fs::path& dst, const char* label) {
        try {
            std::error_code ec{};
            fs::copy_file(src, dst, fs::copy_options::overwrite_existing, ec);
            if (ec) {
                spdlog::error("Failed to copy {}: {}", label, ec.message());
            }
        } catch (const std::filesystem::filesystem_error& e) {
            spdlog::error("Failed to copy {}: {}", label, e.what());
        } catch (const std::exception& e) {
            spdlog::error("Failed to copy {}: {}", label, e.what());
        } catch(...) {
            spdlog::error("Failed to copy {}: unknown exception", label);
        }
    };

    std::error_code directory_ec{};
    for (const auto& entry : fs::directory_iterator(*g_current_game_path, directory_ec)) {
        const auto entry_path = entry.path();
        if (entry.is_regular_file() && entry_path.extension() == ".dll") {
            spdlog::info("Copying DLL file: {}", entry_path.filename().string());
            copy_file_safe(entry_path, dest_path / entry_path.filename().string(), "DLL file");
        }
    }

    if (directory_ec) {
        spdlog::error("An error occurred while traversing the game directory: {}", directory_ec.message());
    }

    const auto d3d12_path = *g_current_game_path / "D3D12" / "D3D12Core.dll";
    if (std::filesystem::exists(d3d12_path)) {
        spdlog::info("Copying D3D12Core.dll file");
        fs::create_directories(dest_path / "D3D12");
        copy_file_safe(d3d12_path, dest_path / "D3D12" / "D3D12Core.dll", "D3D12Core.dll");
    }

    utility::spoof_module_paths_in_exe_dir();
#endif
}

void REFramework::register_ldr_notification() {
    const auto ntdll = GetModuleHandle("ntdll.dll");
    if (ntdll == nullptr) {
        spdlog::info("ntdll.dll not found");
        return;
    }

    spdlog::info("Registering LdrRegisterDllNotification callback...");
    const auto ldr_register_dll_notification = (LdrRegisterDllNotification_t)GetProcAddress(ntdll, "LdrRegisterDllNotification");

    if (ldr_register_dll_notification != nullptr) {
        PVOID cookie = nullptr;
        g_success_made_ldr_notification = NT_SUCCESS(ldr_register_dll_notification(0, ldr_notification_callback, nullptr, &cookie));

        if (g_success_made_ldr_notification) {
            spdlog::info("LdrRegisterDllNotification callback registered successfully");
        } else {
            spdlog::info("LdrRegisterDllNotification callback failed to register");
        }
    } else {
        spdlog::info("LdrRegisterDllNotification not found");
    }
}

void REFramework::wait_for_d3d_if_packed() {
#if defined(REENGINE_PACKED)
    auto now = std::chrono::steady_clock::now();
    std::chrono::steady_clock::time_point next_log = now;

    while (GetModuleHandleA("d3d12.dll") == nullptr) {
        now = std::chrono::steady_clock::now();
        if (now >= next_log) {
            spdlog::info("[REFramework] Waiting for D3D12...");
            next_log = now + 1s;
        }
        Sleep(50);
    }

    while (LoadLibraryA("d3d12.dll") == nullptr) {
        if (now >= next_log) {
            spdlog::info("[REFramework] Waiting for D3D12...");
            next_log = now + 1s;
        }
    }

    spdlog::info("D3D12 loaded");
#endif
}

void REFramework::load_vr_dlls() {
#if defined(MHRISE) || defined(DD2) || TDB_VER >= 74
    LoadLibraryA("dxgi.dll");
    LoadLibraryA("d3d11.dll");

    if (!g_success_made_ldr_notification) {
        utility::spoof_module_paths_in_exe_dir();
    }
#endif
}

void REFramework::setup_re8_crash_fix() {
#if defined(RE8)
    auto startup_lookup_thread = std::make_unique<std::thread>([this]() {
        uint32_t times_searched = 0;

        auto startup_patch_addr = utility::scan(m_game_module, "40 53 57 48 83 ec 28 48 83 b9 ? ? ? ? 00");

        while (!startup_patch_addr) {
            startup_patch_addr = utility::scan(m_game_module, "40 53 57 48 83 ec 28 48 83 b9 ? ? ? ? 00");

            if (times_searched++ > MAX_SCAN_RETRIES) {
                spdlog::error("Failed to find startup patch address");
                return;
            }
        }

        if (startup_patch_addr) {
            spdlog::info("Found startup patch at {:x}", *startup_patch_addr);
            static auto permanent_patch = Patch::create(*startup_patch_addr, {0xC3});
        } else {
            spdlog::info("Couldn't find RE8 crash fix patch location!");
        }
    });
    startup_lookup_thread->detach();
#endif
}

void REFramework::setup_mhwilds_early_init() {
#if defined(MHWILDS)
    FaultyFileDetector::early_init();
#endif
}

void REFramework::setup_integrity_bypass() {
#if defined(REENGINE_AT)
    utility::ThreadSuspender suspender{};
    IntegrityCheckBypass::ignore_application_entries();

#if defined(RE8) || defined(RE4) || defined(SF6)
    IntegrityCheckBypass::immediate_patch_re8();
#endif

#if defined(RE4) || defined(SF6)
    IntegrityCheckBypass::immediate_patch_re4();
#endif

#if defined(DD2) || TDB_VER >= 74
    IntegrityCheckBypass::immediate_patch_dd2();
#endif

#if TDB_VER >= 82
    IntegrityCheckBypass::immediate_patch_re9();
#endif

    IntegrityCheckBypass::remove_stack_destroyer();
    suspender.resume();
#endif
}

void REFramework::plugin_early_init() {
    PluginLoader::get()->early_init();
}

void REFramework::wait_for_vm_and_renderer() {
    const auto start_time = std::chrono::high_resolution_clock::now();

    while (true) {
        try {
            if (sdk::VM::get() != nullptr) break;
        } catch(...) {}

        if (std::chrono::high_resolution_clock::now() - start_time > VM_INIT_TIMEOUT) {
            spdlog::error("Timed out waiting for VM to initialize.");
            throw std::runtime_error("Timed out waiting for VM to initialize.");
        }

        std::this_thread::sleep_for(std::chrono::milliseconds(1));
    }

    spdlog::info("VM initialized, waiting for renderer to initialize...");
    sdk::RETypeDefinition* renderer_t = nullptr;
    sdk::renderer::Renderer* renderer = nullptr;
    bool found_renderer = false;
    bool renderer_has_render_frame_fn = false;

    if (sdk::RETypeDB::get() != nullptr) {
        auto& loader = LooseFileLoader::get();
        auto& integrity_bypass = IntegrityCheckBypass::get_shared_instance();

#if defined(MHWILDS)
        auto& faulty_file_detector = FaultyFileDetector::get();
#endif

        const auto config_path = get_persistent_dir(REFrameworkConfig::REFRAMEWORK_CONFIG_NAME.data()).string();
        if (fs::exists(utility::widen(config_path))) {
            utility::Config cfg{ config_path };
            loader->on_config_load(cfg);

#if defined(MHWILDS)
            faulty_file_detector->on_config_load(cfg);
#endif
            integrity_bypass->on_config_load(cfg);
        }

        if (loader->is_enabled()) {
            loader->hook();
        }
    }

    while (true) try {
        const auto tdb = sdk::RETypeDB::get();

        if (tdb == nullptr) {
            spdlog::error("TypeDB not found");
            break;
        }

        if (renderer_t == nullptr) {
            for (auto i = 0; i < tdb->get_num_types(); ++i) {
                const auto t = tdb->get_type(i);

                if (t == nullptr || t->get_name() == nullptr || t->get_namespace() == nullptr) {
                    continue;
                }

                if (std::string_view{t->get_name()} == "Renderer" &&
                    std::string_view{t->get_namespace()} == "via.render") {
                    spdlog::info("Renderer type found manually @ {:x}", (uintptr_t)t);
                    renderer_t = t;
                    break;
                }
            }
        }

        if (renderer_t == nullptr) {
            spdlog::error("Renderer type not found");
            break;
        }

        renderer_has_render_frame_fn = renderer_t->get_method("get_RenderFrame") != nullptr;

        const auto renderer_has_instance = renderer_t->get_method("hasInstance");
        if (renderer_has_instance == nullptr) {
            spdlog::error("Renderer::hasInstance not found");
            break;
        }

        if (renderer_has_instance->get_function() == nullptr) {
            std::this_thread::sleep_for(std::chrono::milliseconds(1));
            continue;
        }

        const auto has_instance = renderer_has_instance->call<bool>(nullptr, nullptr);
        if (!has_instance) {
            std::this_thread::sleep_for(std::chrono::milliseconds(1));
            continue;
        }

        renderer = sdk::renderer::get_renderer();
        if (renderer != nullptr) {
            found_renderer = true;
            break;
        }

        spdlog::info("waiting for renderer");
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    } catch(...) {
        spdlog::warn("Exception occurred while waiting for renderer");
        continue;
    }

    spdlog::info("Found renderer @ {:x} (type: {:x}), waiting for first frame...",
                 (uintptr_t)renderer, (uintptr_t)renderer_t);

    bool valid_render_frame = false;

    if (renderer_has_render_frame_fn) {
        spdlog::info("Renderer has get_RenderFrame function");
    } else {
        spdlog::info("Renderer does not have get_RenderFrame function");
    }

    while (renderer_has_render_frame_fn) try {
        const auto render_frame = renderer->get_render_frame();

        if (!render_frame.has_value()) {
            spdlog::warn("Render frame property not found");
            break;
        }

        if (*render_frame > 0) {
            spdlog::info("Render frame: {}", *render_frame);
            valid_render_frame = true;
            break;
        }

        std::this_thread::sleep_for(std::chrono::milliseconds(1));
    } catch(...) {
        continue;
    }

    if (valid_render_frame) {
        std::scoped_lock _{m_hook_monitor_mutex};
        hook_d3d12();
    }
}

void REFramework::start_monitor_thread() {
    std::scoped_lock _{m_hook_monitor_mutex};

    m_last_present_time.store(std::chrono::steady_clock::now());
    m_last_message_time.store(std::chrono::steady_clock::now());
    m_d3d_monitor_thread = std::make_unique<std::jthread>([this](std::stop_token stop_token) {
        while (!stop_token.stop_requested() && !m_terminating) {
            this->hook_monitor();
            std::this_thread::sleep_for(std::chrono::milliseconds(500));
        }
    });
}

// ---------------------------------------------------------------------------
// Hook monitor (delegated to extracted HookMonitor class)
// ---------------------------------------------------------------------------
void REFramework::hook_monitor() {
    if (m_hook_monitor) {
        m_hook_monitor->tick();
    }
}

void REFramework::reset_chance_times() {
    if (m_hook_monitor) {
        m_hook_monitor->reset_chance_times();
    }
}

void REFramework::on_message_received() {
    if (m_hook_monitor) {
        m_hook_monitor->on_message_received();
    }
}

// ---------------------------------------------------------------------------
// D3D hook helpers
// ---------------------------------------------------------------------------
template <typename HookType>
bool REFramework::try_hook_renderer(std::unique_ptr<HookType>& hook,
                                     bool& is_current, bool& is_other,
                                     const char* api_name) {
    if (is_other) {
        return false;
    }

    if (hook->hook()) {
        spdlog::info("Hooked {}", api_name);
        m_valid = true;
        is_current = true;
        return true;
    }

    if (hook->unhook()) {
        spdlog::info("{} unhooked!", api_name);
    } else {
        spdlog::info("Cannot unhook {}, this might crash.", api_name);
    }

    m_valid = false;
    is_current = false;
    return false;
}

bool REFramework::hook_d3d11() {
    m_renderer_type = RendererType::D3D11;
    m_d3d11_hook.reset();
    m_d3d11_hook = std::make_unique<D3D11Hook>();
    m_d3d11_hook->on_present([this](D3D11Hook& hook) { on_frame_d3d11(); });
    m_d3d11_hook->on_post_present([this](D3D11Hook& hook) { on_post_present_d3d11(); });
    m_d3d11_hook->on_resize_buffers([this](D3D11Hook& hook) { on_reset(); });

    return try_hook_renderer(m_d3d11_hook, m_is_d3d11, m_is_d3d12, "DirectX 11");
}

bool REFramework::hook_d3d12() {
    m_renderer_type = RendererType::D3D12;

    if (LoadLibraryA("d3d12.dll") == nullptr) {
        spdlog::info("d3d12.dll not found, user is probably running Windows 7.");
        spdlog::info("Falling back to hooking D3D11.");
        m_is_d3d12 = false;
        return hook_d3d11();
    }

    m_d3d12_hook.reset();
    m_d3d12_hook = std::make_unique<D3D12Hook>();
    m_d3d12_hook->on_present([this](D3D12Hook& hook) { on_frame_d3d12(); });
    m_d3d12_hook->on_post_present([this](D3D12Hook& hook) { on_post_present_d3d12(); });
    m_d3d12_hook->on_resize_buffers([this](D3D12Hook& hook) { on_reset(); });
    m_d3d12_hook->on_resize_target([this](D3D12Hook& hook) { on_reset(); });

    if (m_is_d3d11) {
        return false;
    }

    if (!try_hook_renderer(m_d3d12_hook, m_is_d3d12, m_is_d3d11, "DirectX 12")) {
        return hook_d3d11();
    }
    return true;
}

// ---------------------------------------------------------------------------
// Destructor
// ---------------------------------------------------------------------------
REFramework::~REFramework() {
    spdlog::info("REFramework shutting down...");

    m_terminating = true;
    if (m_d3d_monitor_thread != nullptr) {
        m_d3d_monitor_thread->request_stop();
        if (m_d3d_monitor_thread->joinable()) {
            m_d3d_monitor_thread->join();
        }
    }

    m_d3d_monitor_thread.reset();
    m_hook_monitor.reset();
    m_input_manager.reset();

    if (m_is_d3d11) {
        deinit_d3d11();
    }

    if (m_is_d3d12) {
        deinit_d3d12();
    }

    ImGui_ImplWin32_Shutdown();

    if (m_initialized) {
        ImGui::DestroyContext();
    }
}

// ---------------------------------------------------------------------------
// Frame & UI
// ---------------------------------------------------------------------------
void REFramework::run_imgui_frame(bool from_present) {
    std::scoped_lock _{ m_imgui_mtx };

    m_has_frame = false;

    if (!m_initialized) {
        return;
    }

    const bool is_init_ok = m_error.empty() && m_game_data_initialized;

    consume_input();
    init_fonts();
    
    ImGui_ImplWin32_NewFrame();

    if (is_init_ok && !from_present) {
        m_mods->on_pre_imgui_frame();
    }

    ImGui::NewFrame();

    if (!from_present) {
        call_on_frame();
    }

    draw_ui();
    m_last_draw_ui = m_draw_ui;

    IMGUIZMO_NAMESPACE::BeginFrame();

    ImGui::EndFrame();
    ImGui::Render();

    m_has_frame = true;

    if (!from_present && m_wants_save_config) {
        save_config();
        m_wants_save_config = false;
    }
}

bool REFramework::on_frame_common_init() {
    bool is_init_ok = m_error.empty() && m_game_data_initialized;

    if (is_init_ok) {
        if (!std::exchange(m_created_default_cfg, true)) {
            if (!fs::exists({utility::widen(get_persistent_dir(REFrameworkConfig::REFRAMEWORK_CONFIG_NAME.data()).string())})) {
                save_config();
            }
        }
    }

    is_init_ok = first_frame_initialize();
    return is_init_ok;
}

void REFramework::on_reset() {
    std::scoped_lock _{ m_imgui_mtx };

    spdlog::info("Reset!");

    if (m_initialized) {
        // fixes text boxes not being able to receive input
        //imgui::reset_keystates();
    }

    if (m_is_d3d11) {
        deinit_d3d11();
    }

    if (m_is_d3d12) {
        deinit_d3d12();
    }

    if (m_game_data_initialized) {
        m_mods->on_device_reset();
    }

    m_has_frame = false;
    m_first_initialize = false;
    m_initialized = false;
}

// ---------------------------------------------------------------------------
// Input (delegated to InputManager)
// ---------------------------------------------------------------------------
void REFramework::patch_set_cursor_pos() {
    std::scoped_lock _{ m_patch_mtx };

    if (m_set_cursor_pos_patch.get() == nullptr) {
        const auto set_cursor_pos_addr = (uintptr_t)GetProcAddress(GetModuleHandleA("user32.dll"), "SetCursorPos");

        if (set_cursor_pos_addr != 0) {
            spdlog::info("Patching SetCursorPos");
            m_set_cursor_pos_patch = Patch::create(set_cursor_pos_addr, {0xC3});
        }
    }
}

void REFramework::remove_set_cursor_pos_patch() {
    std::scoped_lock _{ m_patch_mtx };

    if (m_set_cursor_pos_patch.get() != nullptr) {
        spdlog::info("Removing SetCursorPos patch");
    }

    m_set_cursor_pos_patch.reset();
}

bool REFramework::on_message(HWND wnd, UINT message, WPARAM w_param, LPARAM l_param) {
    if (m_input_manager) {
        return m_input_manager->on_message(wnd, message, w_param, l_param);
    }
    return true;
}

void REFramework::on_direct_input_keys(const std::array<uint8_t, 256>& keys) {
    if (m_input_manager) {
        m_input_manager->on_direct_input_keys(keys);
    }
}

// ---------------------------------------------------------------------------
// Filesystem / Config
// ---------------------------------------------------------------------------
std::filesystem::path REFramework::get_persistent_dir() {
    static const auto cached_dir = []() -> std::filesystem::path {
        auto return_appdata_dir = []() -> std::filesystem::path {
            char app_data_path[MAX_PATH]{};
            SHGetSpecialFolderPathA(0, app_data_path, CSIDL_APPDATA, false);

            const auto exe_name = std::filesystem::path(
                *utility::get_module_path(utility::get_executable())).stem().string();
            const auto dir = std::filesystem::path(app_data_path) / "REFramework" / exe_name;
            std::filesystem::create_directories(dir);

            return dir;
        };

        try {
            const auto dir = std::filesystem::path(
                *utility::get_module_path(utility::get_executable())).parent_path();
            const auto test_file = dir / "test.txt";
            std::ofstream test_stream{test_file};
            test_stream << "test";
            test_stream.close();

            std::filesystem::create_directories(dir / "test_dir");
            std::filesystem::remove(test_file);
            std::filesystem::remove(dir / "test_dir");

            s_fallback_appdata = false;
            return dir;
        } catch(...) {
            s_fallback_appdata = true;
            return return_appdata_dir();
        }
    }();

    s_checked_file_permissions = true;
    return cached_dir;
}

void REFramework::save_config() {
    std::scoped_lock _{m_config_mtx};

    m_wants_save_config = false;

    spdlog::info("Saving config {}", REFrameworkConfig::REFRAMEWORK_CONFIG_NAME.data());

    utility::Config cfg{};

    for (auto& mod : m_mods->get_mods()) {
        mod->on_config_save(cfg);
    }

    try {
        if (!cfg.save((get_persistent_dir() / REFrameworkConfig::REFRAMEWORK_CONFIG_NAME.data()).string())) {
            spdlog::error("Failed to save config");
            return;
        }
    } catch(const std::exception& e) {
        spdlog::error("Failed to save config: {}", e.what());
        return;
    } catch(...) {
        spdlog::error("Unexpected error while saving config");
        return;
    }

    spdlog::info("Saved config");
}

void REFramework::set_draw_ui(bool state, bool should_save) {
    std::scoped_lock _{m_config_mtx};

    bool prev_state = m_draw_ui;
    m_draw_ui = state;

    if (m_game_data_initialized) {
        REFrameworkConfig::get()->get_menu_open()->value() = state;
    }

    if (state != prev_state && should_save && m_game_data_initialized) {
        save_config();
    }
}

void REFramework::consume_input() {
    if (m_input_manager) {
        m_input_manager->consume_input();
    } else {
        m_mouse_delta[0] = m_accumulated_mouse_delta[0];
        m_mouse_delta[1] = m_accumulated_mouse_delta[1];
        m_accumulated_mouse_delta[0] = 0.0f;
        m_accumulated_mouse_delta[1] = 0.0f;
    }
}

// ---------------------------------------------------------------------------
// Fonts
// ---------------------------------------------------------------------------
int REFramework::add_font(const std::filesystem::path& filepath, float size) {
    for (int i = 0; i < m_additional_fonts.size(); ++i) {
        const auto& font = m_additional_fonts[i];

        if (font.filepath == filepath && abs(font.size - size) < 0.1) {
            return i;
        }
    }

    REFramework::AdditionalFont additional_font{filepath, size};
    if (fs::exists(filepath)) {
        auto path = filepath.string();
        if (!loaded_fonts.contains(path)) {
            loaded_fonts[path] = ImGui::GetIO().Fonts->AddFontFromFileTTF(path.c_str(), size);
        }
        additional_font.font = loaded_fonts[path];
    } else {
        additional_font.font = m_default_font;
    }

    m_additional_fonts.emplace_back(additional_font);
    
    return m_additional_fonts.size() - 1;
}

void REFramework::init_fonts() {
    if (!m_fonts_need_init) {
        return;
    }

    m_fonts_need_init = false;

    auto& fonts = ImGui::GetIO().Fonts;
    fonts->FontLoader = ImGuiFreeType::GetFontLoader();

    ImFontConfig custom_icons{};
    custom_icons.FontDataOwnedByAtlas = false;

    const auto fonts_path = REFramework::get_persistent_dir() / "reframework" / "fonts";
    const auto font_path = fonts_path / m_default_font_file;

    auto load_seguiemj_font = [&]() {   
        try {
            wchar_t windows_dir[MAX_PATH]{};
            if (GetWindowsDirectoryW(windows_dir, MAX_PATH) == 0) {
                spdlog::error("Failed to get system directory");
                return;
            }

            const auto seguiemj_path = std::filesystem::path(windows_dir) / "Fonts" / "seguiemj.ttf";

            if (std::filesystem::exists(seguiemj_path)) {
                spdlog::info("Loading Segoe UI Emoji font from: {}", seguiemj_path.string());

                ImFontConfig cfg{};
                cfg.FontDataOwnedByAtlas = true;
                cfg.FontLoaderFlags |= ImGuiFreeTypeLoaderFlags_LoadColor;
                cfg.MergeMode        = true;
                fonts->AddFontFromFileTTF(seguiemj_path.string().c_str(), m_font_size, &cfg);
            } else {
                spdlog::warn("Segoe UI Emoji font not found");
            }
        } catch (const std::exception& e) {
            spdlog::error("Failed to load default font: {}", e.what());
            m_default_font_file = "DEFAULT";
        }
    };

    if (fs::exists(font_path)) {
        if (!loaded_fonts.contains(m_default_font_file)) {
            ImFontConfig cfg{};
            cfg.FontDataOwnedByAtlas = true;
            cfg.MergeMode = false;

            loaded_fonts[m_default_font_file] = fonts->AddFontFromFileTTF(font_path.string().c_str(), m_font_size, &cfg);
        }

        if (loaded_fonts[m_default_font_file] == nullptr) {
            spdlog::error("Failed to load font: {}", font_path.string());
            m_default_font = nullptr;
        } else {
            spdlog::info("Loaded font: {}", m_default_font_file);
            load_seguiemj_font();
            m_default_font = loaded_fonts[m_default_font_file];
        }
    } else {
        if (m_default_font_file != "DEFAULT") {
            spdlog::error("Font file not found: {}", font_path.string());
            spdlog::warn("Falling back to system default font");
        }

        if (!loaded_fonts.contains("DEFAULT")) {
            loaded_fonts["DEFAULT"] = fonts->AddFontDefault();
            spdlog::info("Using system default font");
        }
        load_seguiemj_font();
        m_default_font = loaded_fonts["DEFAULT"];
    }
}

void REFramework::invalidate_device_objects() {
    if (!m_wants_device_object_cleanup) {
        return;
    }

    if (m_renderer_type == RendererType::D3D11) {
        ImGui_ImplDX11_InvalidateDeviceObjects();
    } else if (m_renderer_type == RendererType::D3D12) {
        ImGui_ImplDX12_InvalidateDeviceObjects();
    }

    m_wants_device_object_cleanup = false;
}

// ---------------------------------------------------------------------------
// UI
// ---------------------------------------------------------------------------
void REFramework::draw_ui() {
    std::lock_guard _{m_input_mutex};

    ImGui::GetIO().MouseDrawCursor = m_draw_ui && REFrameworkConfig::get()->is_always_show_cursor();
    ImGui::GetIO().ConfigFlags |= ImGuiConfigFlags_NoMouseCursorChange;

    if (!m_draw_ui) {
        remove_set_cursor_pos_patch();

        m_is_ui_focused = false;
        if (m_last_draw_ui) {
            m_windows_message_hook->window_toggle_cursor(m_cursor_state);
        }
        m_dinput_hook->acknowledge_input();
        return;
    } else {
        patch_set_cursor_pos();
    }
    
    m_is_ui_focused = ImGui::IsWindowFocused(ImGuiFocusedFlags_AnyWindow);

    if (m_ui_option_transparent) {
        auto& style = ImGui::GetStyle();
        if (m_is_ui_focused) {
            style.Alpha = 1.0f;
        } else {
            if (ImGui::IsWindowHovered(ImGuiFocusedFlags_AnyWindow)) {
                style.Alpha = 0.9f;
            } else {
                style.Alpha = 0.8f;
            }
        }
    } else {
        auto& style = ImGui::GetStyle();
        style.Alpha = 1.0f;
    }

    auto& io = ImGui::GetIO();

    if (io.WantCaptureKeyboard) {
        m_dinput_hook->ignore_input();
    } else {
        m_dinput_hook->acknowledge_input();
    }

    if (!m_last_draw_ui || m_cursor_state_changed) {
        m_cursor_state_changed = false;
        m_windows_message_hook->window_toggle_cursor(true);
    }

    ImGui::SetNextWindowPos(ImVec2(50, 50), ImGuiCond_::ImGuiCond_FirstUseEver);
    ImGui::SetNextWindowSize(ImVec2(300, 500), ImGuiCond_::ImGuiCond_FirstUseEver);

    ImFont* font_to_use = m_default_font;
    if (font_to_use == nullptr) {
        font_to_use = ImGui::GetIO().FontDefault;
        if (font_to_use == nullptr) {
            font_to_use = ImGui::GetIO().Fonts->Fonts.empty() ? nullptr : ImGui::GetIO().Fonts->Fonts[0];
        }
    }
    ImGui::PushFont(font_to_use, m_font_size);
    static const std::string REF_NAME = "REFramework";
    bool is_open = true;
    ImGui::Begin(REF_NAME.c_str(), &is_open);
    ImGui::Text("Default Menu Key: Insert");
    ImGui::Checkbox("Transparency", &m_ui_option_transparent);
    ImGui::SameLine();
    ImGui::Text("(?)");
    if (ImGui::IsItemHovered())
        ImGui::SetTooltip("Makes the UI transparent when not focused.");
    ImGui::Checkbox("Input Passthrough", &m_ui_passthrough);
    ImGui::SameLine();
    ImGui::Text("(?)");
    if (ImGui::IsItemHovered())
        ImGui::SetTooltip("Allows mouse and keyboard inputs to register to the game while the UI is focused.");

    if (m_error.empty() && m_game_data_initialized) {
        m_mods->on_draw_ui();
    } else if (!m_game_data_initialized) {
        ImGui::TextWrapped("REFramework is currently initializing...");
        ImGui::TextWrapped("This menu will close after initialization if you have the remember option enabled.");
    } else if (!m_error.empty()) {
        ImGui::TextWrapped("REFramework error: %s", m_error.c_str());
    }

    m_last_window_pos = ImGui::GetWindowPos();
    m_last_window_size = ImGui::GetWindowSize();

    ImGui::PopFont();
    ImGui::End();

    if (!is_open) {
        set_draw_ui(is_open, true);
    } else if (m_draw_ui != m_last_draw_ui) {
        set_draw_ui(m_draw_ui, true);
    }

    if (m_last_draw_ui && !m_draw_ui) {
        m_windows_message_hook->window_toggle_cursor(m_cursor_state);
    }
}

void REFramework::set_imgui_style() noexcept {
    ImGui::StyleColorsDark();

    auto& style = ImGui::GetStyle();
    style.WindowRounding = 0.0f;
    style.ChildRounding = 0.0f;
    style.PopupRounding = 0.0f;
    style.FrameRounding = 0.0f;
    style.ScrollbarRounding = 2.0f;
    style.GrabRounding = 0.0f;
    style.TabRounding = 0.0f;
    style.WindowBorderSize = 2.0f;
    style.WindowPadding = ImVec2(2.0f, 0.0f);

    auto& colors = ImGui::GetStyle().Colors;
    colors[ImGuiCol_WindowBg] = ImVec4{0.1f, 0.105f, 0.11f, 1.0f};
    colors[ImGuiCol_NavCursor] = ImVec4{0.3f, 0.305f, 0.31f, 1.0f};
    colors[ImGuiCol_PlotHistogram] = ImVec4{0.3f, 0.305f, 0.31f, 1.0f};
    colors[ImGuiCol_Header] = ImVec4{0.2f, 0.205f, 0.21f, 1.0f};
    colors[ImGuiCol_HeaderHovered] = ImVec4{0.3f, 0.305f, 0.31f, 1.0f};
    colors[ImGuiCol_HeaderActive] = ImVec4{0.55f, 0.5505f, 0.551f, 1.0f};
    colors[ImGuiCol_Button] = ImVec4{0.2f, 0.205f, 0.21f, 1.0f};
    colors[ImGuiCol_ButtonHovered] = ImVec4{0.3f, 0.305f, 0.31f, 1.0f};
    colors[ImGuiCol_ButtonActive] = ImVec4{0.55f, 0.5505f, 0.551f, 1.0f};
    colors[ImGuiCol_CheckMark] = ImVec4(0.55f, 0.5505f, 0.551f, 1.0f);
    colors[ImGuiCol_FrameBg] = ImVec4{0.211f, 0.210f, 0.25f, 1.0f};
    colors[ImGuiCol_FrameBgHovered] = ImVec4{0.3f, 0.305f, 0.31f, 1.0f};
    colors[ImGuiCol_FrameBgActive] = ImVec4{0.55f, 0.5505f, 0.551f, 1.0f};
    colors[ImGuiCol_Tab] = ImVec4{0.25f, 0.2505f, 0.251f, 1.0f};
    colors[ImGuiCol_TabHovered] = ImVec4{0.38f, 0.3805f, 0.381f, 1.0f};
    colors[ImGuiCol_TabSelected] = ImVec4{0.28f, 0.2805f, 0.281f, 1.0f};
    colors[ImGuiCol_TabDimmed] = ImVec4{0.25f, 0.2505f, 0.251f, 1.0f};
    colors[ImGuiCol_TabDimmedSelected] = ImVec4{0.8f, 0.805f, 0.81f, 1.0f};
    colors[ImGuiCol_ResizeGrip] = ImVec4{0.2f, 0.205f, 0.21f, 0.0f};
    colors[ImGuiCol_ResizeGripHovered] = ImVec4{0.3f, 0.305f, 0.31f, 1.0f};
    colors[ImGuiCol_ResizeGripActive] = ImVec4{0.55f, 0.5505f, 0.551f, 1.0f};
    colors[ImGuiCol_TitleBg] = ImVec4{0.25f, 0.2505f, 0.251f, 1.0f};
    colors[ImGuiCol_TitleBgActive] = ImVec4{0.55f, 0.5505f, 0.551f, 1.0f};
    colors[ImGuiCol_TitleBgCollapsed] = ImVec4{0.25f, 0.2505f, 0.251f, 1.0f};

    set_font_size(m_font_size);
}

// ---------------------------------------------------------------------------
// Initialization
// ---------------------------------------------------------------------------
bool REFramework::initialize() {
    if (m_initialized) {
        return true;
    }

    reframework::setup_exception_handler();

    if (m_first_initialize) {
        m_frames_since_init = 0;
        m_first_initialize = false;
    }

    if (m_frames_since_init < INIT_FRAME_DELAY) {
        m_frames_since_init++;
        return false;
    }

    if (m_is_d3d11) {
        spdlog::info("Attempting to initialize DirectX 11");

        if (!m_d3d11_hook->is_hooked()) {
            return false;
        }

        auto device = m_d3d11_hook->get_device();
        auto swap_chain = m_d3d11_hook->get_swap_chain();

        if (device == nullptr || swap_chain == nullptr) {
            m_first_initialize = true;

            spdlog::info("Device or SwapChain null. DirectX 12 may be in use. Unhooking D3D11...");

            if (m_d3d11_hook->unhook()) {
                spdlog::info("D3D11 unhooked!");
            } else {
                spdlog::error("Cannot unhook D3D11, this might crash.");
            }

            m_is_d3d11 = false;
            m_valid = false;

            if (!hook_d3d12()) {
                spdlog::error("Failed to hook D3D12 after unhooking D3D11.");
            }
            return false;
        }

        ID3D11DeviceContext* context = nullptr;
        device->GetImmediateContext(&context);

        DXGI_SWAP_CHAIN_DESC swap_desc{};
        swap_chain->GetDesc(&swap_desc);

        m_wnd = swap_desc.OutputWindow;

        spdlog::info("Window Handle: {0:x}", (uintptr_t)m_wnd);
        spdlog::info("Initializing ImGui");

        IMGUI_CHECKVERSION();
        ImGui::CreateContext();
        ImNodes::SetImGuiContext(ImGui::GetCurrentContext());
        ImNodes::CreateContext();

        set_imgui_style();

        static const auto imgui_ini = (get_persistent_dir() / "ref_ui.ini").string();
        ImGui::GetIO().IniFilename = imgui_ini.c_str();

        spdlog::info("Initializing ImGui Win32");

        if (!ImGui_ImplWin32_Init(m_wnd)) {
            spdlog::error("Failed to initialize ImGui.");
            return false;
        }

        spdlog::info("Creating render target");

        if (!init_d3d11()) {
            spdlog::error("Failed to init D3D11");
            return false;
        }
    } else if (m_is_d3d12) {
        spdlog::info("Attempting to initialize DirectX 12");

        if (!m_d3d12_hook->is_hooked()) {
            return false;
        }

        auto device = m_d3d12_hook->get_device();
        auto swap_chain = m_d3d12_hook->get_swap_chain();

        if (device == nullptr || swap_chain == nullptr) {
            m_first_initialize = true;

            spdlog::info("Device: {:x}", (uintptr_t)device);
            spdlog::info("SwapChain: {:x}", (uintptr_t)swap_chain);

            spdlog::info("Device or SwapChain null. DirectX 11 may be in use. Unhooking D3D12...");

            if (m_d3d12_hook->unhook())
                spdlog::info("D3D12 unhooked!");
            else
                spdlog::error("Cannot unhook D3D12, this might crash.");

            m_valid = false;
            m_is_d3d12 = false;

            if (!hook_d3d11()) {
                spdlog::error("Failed to hook D3D11 after unhooking D3D12.");
            }
            return false;
        }

        DXGI_SWAP_CHAIN_DESC swap_desc{};
        swap_chain->GetDesc(&swap_desc);

        m_wnd = swap_desc.OutputWindow;

        IMGUI_CHECKVERSION();
        ImGui::CreateContext();
        ImNodes::SetImGuiContext(ImGui::GetCurrentContext());
        ImNodes::CreateContext();

        set_imgui_style();

        static const auto imgui_ini = (get_persistent_dir() / "ref_ui.ini").string();
        ImGui::GetIO().IniFilename = imgui_ini.c_str();
        
        if (!ImGui_ImplWin32_Init(m_wnd)) {
            spdlog::error("Failed to initialize ImGui ImplWin32.");
            return false;
        }

        if (!init_d3d12()) {
            spdlog::error("Failed to init D3D12.");
            return false;
        }
    } else {
        return false;
    }

    initialize_windows_message_hook();

    if (m_first_frame) {
        m_dinput_hook = std::make_unique<DInputHook>(m_wnd);
    } else {
        m_dinput_hook->set_window(m_wnd);
    }

    if (m_first_frame) {
        m_first_frame = false;
        initialize_game_data();
    }

    return true;
}

bool REFramework::initialize_game_data() {
    if (m_game_data_initialized || m_started_game_data_thread) {
        return true;
    }

    m_started_game_data_thread = true;

    spdlog::info("Starting game data initialization thread");

    std::thread init_thread([this]() {
        std::scoped_lock _{this->m_startup_mutex};

        try {
#if defined(MHRISE) || defined(DD2) || TDB_VER >= 74
            if (!g_success_made_ldr_notification) {
                utility::spoof_module_paths_in_exe_dir();
            }
#endif
            reframework::initialize_sdk();

#if TDB_VER >= 71
            const auto start_time = std::chrono::high_resolution_clock::now();

            while (true) {
                try {
                    if (sdk::VM::get() != nullptr) {
                        break;
                    }
                } catch(...) {
                }

                if (std::chrono::high_resolution_clock::now() - start_time > std::chrono::seconds(30)) {
                    spdlog::error("Timed out waiting for VM to initialize.");
                    throw std::runtime_error("Timed out waiting for VM to initialize.");
                }

                std::this_thread::sleep_for(std::chrono::milliseconds(100));
            }

            while (true) {
                try {
                    if (sdk::Application::get() != nullptr) {
                        break;
                    }
                } catch(...) {
                }

                if (std::chrono::high_resolution_clock::now() - start_time > std::chrono::seconds(30)) {
                    spdlog::error("Timed out waiting for Application to initialize.");
                    throw std::runtime_error("Timed out waiting for Application to initialize.");
                }

                std::this_thread::sleep_for(std::chrono::milliseconds(100));
            }
#endif

            m_mods = std::make_unique<Mods>();

            auto e = m_mods->on_initialize();

            if (e) {
                if (e->empty()) {
                    m_error = "An unknown error has occurred.";
                } else {
                    m_error = *e;
                }

                spdlog::error("Initialization of mods failed. Reason: {}", m_error);
            }

            if (auto context = sdk::get_thread_context(); context != nullptr) try {
                context->local_frame_gc();
            } catch(...) {
                spdlog::error("Failed to run local frame GC.");
            }

            m_game_data_initialized = true;
        } catch(const std::exception& e) {
            m_error = e.what();
            m_game_data_initialized = true;
            spdlog::error("Initialization of mods failed. Reason: {}", m_error);
        }
        catch(...) {
            m_error = "An exception has occurred during initialization.";
            m_game_data_initialized = true;
            spdlog::error("Initialization of mods failed. Reason: exception thrown.");
        }

#if defined(MHRISE) || defined(DD2) || TDB_VER >= 74
        if (!g_success_made_ldr_notification) {
            utility::spoof_module_paths_in_exe_dir();
        }
#endif
        spdlog::info("Game data initialization thread finished");
    });

    init_thread.detach();

    return true;
}

bool REFramework::initialize_windows_message_hook() {
    if (m_wnd == 0) {
        return false;
    }

    if (m_first_frame || m_message_hook_requested.load() || m_windows_message_hook == nullptr) {
        m_last_message_time.store(std::chrono::steady_clock::now());
        m_windows_message_hook.reset();
        m_windows_message_hook = std::make_unique<WindowsMessageHook>(m_wnd);
        m_windows_message_hook->on_message = [this](auto wnd, auto msg, auto w_param, auto l_param) {
            return on_message(wnd, msg, w_param, l_param);
        };

        m_message_hook_requested.store(false);
        return true;
    }

    m_message_hook_requested.store(false);
    return false;
}

bool REFramework::first_frame_initialize() {
    const bool is_init_ok = m_error.empty() && m_game_data_initialized;

    if (!is_init_ok || !m_first_frame_d3d_initialize) {
        return is_init_ok;
    }

    auto do_not_hook_d3d = acquire_do_not_hook_d3d();

    spdlog::info("Running first frame D3D initialization of mods...");

    m_first_frame_d3d_initialize = false;
    auto e = m_mods->on_initialize_d3d_thread();

    if (e) {
        if (e->empty()) {
            m_error = "An unknown error has occurred.";
        } else {
            m_error = *e;
        }

        spdlog::error("Initialization of mods failed. Reason: {}", m_error);
        m_game_data_initialized = false;
        m_mods_fully_initialized = false;
        return false;
    } else {
        save_config();
        m_mods_fully_initialized = true;
    }

    try {
        spdlog::info("Logging loaded modules...");

        const auto loaded_modules = utility::get_loaded_module_names();

        for (const auto& name : loaded_modules) {
            spdlog::info("Loaded module: {}", utility::narrow(name));
        }
    } catch(...) {
        spdlog::error("Failed to get loaded modules.");
    }

    return true;
}

void REFramework::call_on_frame() {
    const bool is_init_ok = m_error.empty() && m_game_data_initialized;

    if (is_init_ok) {
        m_mods->on_frame();
    }
}
